import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { sourceOnlyGateReason } from '../src/catalog/action-gates.js';
import { joomlaActions } from '../src/catalog/action-catalog.js';
import {
  supportsCompanionReadAction,
  supportsCompanionWriteAction,
} from '../src/catalog/companion-actions.js';

const outputPath = resolve('docs/API_ACTIONS.md');
const generated = render();

if (process.argv.includes('--check')) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== generated) {
    process.stderr.write('docs/API_ACTIONS.md is stale; run npm run docs:actions.\\n');
    process.exitCode = 1;
  }
} else {
  writeFileSync(outputPath, generated, 'utf8');
}

function render(): string {
  const lines = [
    '# Joomla Web Services action reference',
    '',
    '> Generated from the reviewed action catalogue. Do not edit this file directly; run `npm run docs:actions`.',
    '',
    'The edge catalogue contains every Joomla 6.1 core Web Services route template: 236 semantic actions across 36 CRUD bases and 56 special routes. A row marked **source-only** is registered by Joomla source but intentionally unavailable because the native route is defective or cannot yet be exposed without secrets. “Executable” does not mean live-certified; see [Coverage](COVERAGE.md).',
    '',
    '| Measure | Count |',
    '|---|---:|',
    `| Source-backed route templates | ${joomlaActions.length} |`,
    `| Read actions | ${joomlaActions.filter((action) => action.method === 'GET').length} |`,
    `| Write actions | ${joomlaActions.filter((action) => action.method !== 'GET').length} |`,
    `| Source-only gated actions | ${joomlaActions.filter((action) => sourceOnlyGateReason(action.id) !== undefined).length} |`,
    '',
    'Use `joomla_actions_search` to find actions available to a configured site and actor, then `joomla_action_describe` to retrieve the complete machine-readable schema, source reference, ACL hints, availability, and certification state.',
    '',
    'The table lists static reviewed fields. API create/update plans for `content.articles`, `content.categories`, `contacts.contacts` and `users.users` also accept published custom fields resolved on the selected site, with the matching field-list read authorization (`structure.read`, or `users.read` for users). Their names/types appear in site-specific action descriptions; the static catalogue remains closed. See [Writing custom field values](CUSTOM_FIELDS.md) for aliases, controller-specific bodies, limits and testing.',
    '',
  ];
  const domains = [...new Set(joomlaActions.map((action) => action.domain))].sort();

  for (const domain of domains) {
    lines.push(`## ${title(domain)}`, '');
    lines.push('| Semantic action | Method and Joomla route | Input contract | Toolset / risk | Paths | Status |');
    lines.push('|---|---|---|---|---|---|');

    for (const action of joomlaActions
      .filter((candidate) => candidate.domain === domain)
      .sort((left, right) => left.id.localeCompare(right.id))) {
      const read = action.method === 'GET';
      const companion = read
        ? supportsCompanionReadAction(action.id)
        : supportsCompanionWriteAction(action.id);
      const gate = sourceOnlyGateReason(action.id);
      const paths = gate === undefined
        ? companion ? 'API, companion' : 'API'
        : 'None';
      const status = gate === undefined
        ? 'Executable; live certification pending'
        : `**Source-only:** ${gate}`;

      lines.push(
        `| \`${action.id}\` | \`${action.method} ${action.routeTemplate}\` | ${inputContract(action)} | ` +
        `\`${action.toolset}\` / ${action.risk} | ${paths} | ${escapeCell(status)} |`,
      );
    }

    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function inputContract(action: (typeof joomlaActions)[number]): string {
  const route = action.routeParameters.length === 0
    ? []
    : action.routeParameters.map((parameter) => `\`${parameter.name}\``);
  const inputs = [...route];

  if (action.method === 'GET') {
    if (action.paginated) inputs.push('bounded `offset`, `limit`');
    return inputs.length === 0 ? 'No input' : inputs.join(', ');
  }

  const data = action.inputSchema.properties['data'];
  if (data !== undefined) {
    const fields = isRecord(data['properties']) ? Object.keys(data['properties']).sort() : [];
    if (fields.length > 0) {
      inputs.push(`data: ${fields.map((field) => `\`${field}\``).join(', ')}`);
      if (data['additionalProperties'] === true) inputs.push('plus Joomla runtime fields');
    } else {
      inputs.push('bounded Joomla form data');
    }
  }
  if (action.inputSchema.properties['etag'] !== undefined) inputs.push('optional `etag`');
  return inputs.length === 0 ? 'No body' : inputs.join('; ');
}

function title(value: string): string {
  return value
    .split('-')
    .map((part) => `${part.charAt(0).toLocaleUpperCase('en')}${part.slice(1)}`)
    .join(' ');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
